[data]
base_path = "/share/lazy/Mohamed/Bu2LambdaPPP/files/data"
magnets = ["MD", "MU"]
years = ["2016", "2017", "2018"]  # Strings for consistency with dict keys

[mc]
base_path = "/share/lazy/Mohamed/Bu2LambdaPPP/files/mc"
states = ["Jpsi", "etac", "chic0", "chic1", "KpKm"]

[output]
docs_dir = "./docs"
plots_dir = "./plots"
results_dir = "./results"
tables_dir = "./tables"
